version: '3.8'

services:
  gestor-cursos:
    build:
      context: https://github.com/Nachovels/microGestorCursos.git
    container_name: gestor-cursos
    ports:
      - "8080:8080"  # puerto interno 8080 → externo 8080

  reportes:
    build:
      context: https://github.com/Nachovels/microReportes.git
    container_name: micro-reportes
    ports:
      - "8081:8081"  # puerto interno 8081 → externo 8081
