version: '3.8'

services:
  gestor-cursos:
    build:
      context: https://github.com/Nachovels/microGestorCursos.git
    container_name: gestor-cursos
    expose:
      - "8080"
    networks:
      - backend

  reportes:
    build:
      context: https://github.com/Nachovels/microReportes.git
    container_name: micro-reportes
    expose:
      - "8081"
    networks:
      - backend

  micro-usuarios:
    build:
      context: https://github.com/Ignaciofuen/microdeusuarios.git
    container_name: micro-usuarios
    expose:
      - "8082"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gestor-cursos
      - reportes
      - micro-usuarios
    networks:
      - backend

networks:
  backend:
