name: deploy-microservicios

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar este repositorio de despliegue
        uses: actions/checkout@v3

      - name: Conectarse e instalar Docker + Compose + desplegar microservicios
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu

            # Instalar Docker si no está
            if ! command -v docker &> /dev/null; then
              echo "Instalando Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            # Instalar Docker Compose si no está
            if ! command -v docker-compose &> /dev/null; then
              echo "Instalando Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Eliminar despliegue anterior y volver a clonar
            sudo rm -rf despliegue-microservicios
            sudo git clone https://github.com/Nachovels/despliegue-microservicios.git
            cd despliegue-microservicios

            # Desplegar servicios
            sudo docker-compose down || true
            sudo docker-compose up -d --build
            echo "Despliegue completado."